// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum HapticKind { selection, impact, outcome, sequence }

enum HapticLevel { light, medium, heavy }

enum HapticResult { success, warning, error }

class HapticPulse {
  HapticPulse({required this.atMillis, required this.strength});

  int atMillis;

  HapticLevel strength;

  List<Object?> _toList() {
    return <Object?>[atMillis, strength];
  }

  Object encode() {
    return _toList();
  }

  static HapticPulse decode(Object result) {
    result as List<Object?>;
    return HapticPulse(
      atMillis: result[0]! as int,
      strength: result[1]! as HapticLevel,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HapticPulse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(atMillis, other.atMillis) &&
        _deepEquals(strength, other.strength);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HapticPulse(atMillis: $atMillis, strength: $strength)';
  }
}

class HapticRequest {
  HapticRequest({
    required this.id,
    required this.kind,
    this.strength,
    this.outcome,
    required this.pulses,
  });

  int id;

  HapticKind kind;

  HapticLevel? strength;

  HapticResult? outcome;

  List<HapticPulse> pulses;

  List<Object?> _toList() {
    return <Object?>[id, kind, strength, outcome, pulses];
  }

  Object encode() {
    return _toList();
  }

  static HapticRequest decode(Object result) {
    result as List<Object?>;
    return HapticRequest(
      id: result[0]! as int,
      kind: result[1]! as HapticKind,
      strength: result[2] as HapticLevel?,
      outcome: result[3] as HapticResult?,
      pulses: (result[4]! as List<Object?>).cast<HapticPulse>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HapticRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(strength, other.strength) &&
        _deepEquals(outcome, other.outcome) &&
        _deepEquals(pulses, other.pulses);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HapticRequest(id: $id, kind: $kind, strength: $strength, outcome: $outcome, pulses: $pulses)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is HapticKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is HapticLevel) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is HapticResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is HapticPulse) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is HapticRequest) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : HapticKind.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : HapticLevel.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : HapticResult.values[value];
      case 132:
        return HapticPulse.decode(readValue(buffer)!);
      case 133:
        return HapticRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class OwlHapticsHostApi {
  /// Constructor for [OwlHapticsHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  OwlHapticsHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> play(HapticRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.owl_haptics.OwlHapticsHostApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> cancel(int id) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.owl_haptics.OwlHapticsHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stop() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.owl_haptics.OwlHapticsHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
