// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum NativeAdType {
  reward,
  insert,
}

enum NativeEventKind {
  loaded,
  shown,
  clicked,
  closed,
  failed,
  rewarded,
  revenue,
  unknown,
}

class NativeConsent {
  NativeConsent({
    required this.accepted,
    required this.personalizedAds,
  });

  bool accepted;

  bool personalizedAds;

  List<Object?> _toList() {
    return <Object?>[
      accepted,
      personalizedAds,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeConsent decode(Object result) {
    result as List<Object?>;
    return NativeConsent(
      accepted: result[0]! as bool,
      personalizedAds: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeConsent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accepted, other.accepted) && _deepEquals(personalizedAds, other.personalizedAds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeConsent(accepted: $accepted, personalizedAds: $personalizedAds)';
  }
}

class NativeAccess {
  NativeAccess({
    required this.canUseLocation,
    required this.canUsePhoneState,
    required this.canUseWifiState,
    required this.canUseWriteExternalStorage,
    required this.canUseOaid,
    required this.canUseAndroidId,
    required this.canUseInstalledApps,
    required this.canUseRecordAudio,
    required this.canUseIdfa,
    required this.canUploadDeviceInfo,
  });

  bool canUseLocation;

  bool canUsePhoneState;

  bool canUseWifiState;

  bool canUseWriteExternalStorage;

  bool canUseOaid;

  bool canUseAndroidId;

  bool canUseInstalledApps;

  bool canUseRecordAudio;

  bool canUseIdfa;

  bool canUploadDeviceInfo;

  List<Object?> _toList() {
    return <Object?>[
      canUseLocation,
      canUsePhoneState,
      canUseWifiState,
      canUseWriteExternalStorage,
      canUseOaid,
      canUseAndroidId,
      canUseInstalledApps,
      canUseRecordAudio,
      canUseIdfa,
      canUploadDeviceInfo,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAccess decode(Object result) {
    result as List<Object?>;
    return NativeAccess(
      canUseLocation: result[0]! as bool,
      canUsePhoneState: result[1]! as bool,
      canUseWifiState: result[2]! as bool,
      canUseWriteExternalStorage: result[3]! as bool,
      canUseOaid: result[4]! as bool,
      canUseAndroidId: result[5]! as bool,
      canUseInstalledApps: result[6]! as bool,
      canUseRecordAudio: result[7]! as bool,
      canUseIdfa: result[8]! as bool,
      canUploadDeviceInfo: result[9]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAccess || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(canUseLocation, other.canUseLocation) && _deepEquals(canUsePhoneState, other.canUsePhoneState) && _deepEquals(canUseWifiState, other.canUseWifiState) && _deepEquals(canUseWriteExternalStorage, other.canUseWriteExternalStorage) && _deepEquals(canUseOaid, other.canUseOaid) && _deepEquals(canUseAndroidId, other.canUseAndroidId) && _deepEquals(canUseInstalledApps, other.canUseInstalledApps) && _deepEquals(canUseRecordAudio, other.canUseRecordAudio) && _deepEquals(canUseIdfa, other.canUseIdfa) && _deepEquals(canUploadDeviceInfo, other.canUploadDeviceInfo);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAccess(canUseLocation: $canUseLocation, canUsePhoneState: $canUsePhoneState, canUseWifiState: $canUseWifiState, canUseWriteExternalStorage: $canUseWriteExternalStorage, canUseOaid: $canUseOaid, canUseAndroidId: $canUseAndroidId, canUseInstalledApps: $canUseInstalledApps, canUseRecordAudio: $canUseRecordAudio, canUseIdfa: $canUseIdfa, canUploadDeviceInfo: $canUploadDeviceInfo)';
  }
}

class NativeInitializationRequest {
  NativeInitializationRequest({
    required this.appId,
    required this.consent,
    required this.access,
    required this.debugLogging,
  });

  String appId;

  NativeConsent consent;

  NativeAccess access;

  bool debugLogging;

  List<Object?> _toList() {
    return <Object?>[
      appId,
      consent,
      access,
      debugLogging,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeInitializationRequest decode(Object result) {
    result as List<Object?>;
    return NativeInitializationRequest(
      appId: result[0]! as String,
      consent: result[1]! as NativeConsent,
      access: result[2]! as NativeAccess,
      debugLogging: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeInitializationRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(appId, other.appId) && _deepEquals(consent, other.consent) && _deepEquals(access, other.access) && _deepEquals(debugLogging, other.debugLogging);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeInitializationRequest(appId: $appId, consent: $consent, access: $access, debugLogging: $debugLogging)';
  }
}

class NativePrivacyUpdate {
  NativePrivacyUpdate({
    required this.consent,
    required this.access,
  });

  NativeConsent consent;

  NativeAccess access;

  List<Object?> _toList() {
    return <Object?>[
      consent,
      access,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativePrivacyUpdate decode(Object result) {
    result as List<Object?>;
    return NativePrivacyUpdate(
      consent: result[0]! as NativeConsent,
      access: result[1]! as NativeAccess,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePrivacyUpdate || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(consent, other.consent) && _deepEquals(access, other.access);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativePrivacyUpdate(consent: $consent, access: $access)';
  }
}

class NativeRewardOptions {
  NativeRewardOptions({
    this.userId,
    this.rewardName,
    this.rewardAmount,
    this.customData,
  });

  String? userId;

  String? rewardName;

  int? rewardAmount;

  String? customData;

  List<Object?> _toList() {
    return <Object?>[
      userId,
      rewardName,
      rewardAmount,
      customData,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeRewardOptions decode(Object result) {
    result as List<Object?>;
    return NativeRewardOptions(
      userId: result[0] as String?,
      rewardName: result[1] as String?,
      rewardAmount: result[2] as int?,
      customData: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeRewardOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(userId, other.userId) && _deepEquals(rewardName, other.rewardName) && _deepEquals(rewardAmount, other.rewardAmount) && _deepEquals(customData, other.customData);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeRewardOptions(userId: $userId, rewardName: $rewardName, rewardAmount: $rewardAmount, customData: $customData)';
  }
}

class NativeAdRequest {
  NativeAdRequest({
    required this.placement,
    required this.adType,
    required this.codeId,
    required this.generation,
    this.rewardOptions,
  });

  String placement;

  NativeAdType adType;

  String codeId;

  int generation;

  NativeRewardOptions? rewardOptions;

  List<Object?> _toList() {
    return <Object?>[
      placement,
      adType,
      codeId,
      generation,
      rewardOptions,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAdRequest decode(Object result) {
    result as List<Object?>;
    return NativeAdRequest(
      placement: result[0]! as String,
      adType: result[1]! as NativeAdType,
      codeId: result[2]! as String,
      generation: result[3]! as int,
      rewardOptions: result[4] as NativeRewardOptions?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAdRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(placement, other.placement) && _deepEquals(adType, other.adType) && _deepEquals(codeId, other.codeId) && _deepEquals(generation, other.generation) && _deepEquals(rewardOptions, other.rewardOptions);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAdRequest(placement: $placement, adType: $adType, codeId: $codeId, generation: $generation, rewardOptions: $rewardOptions)';
  }
}

class NativeAdIdentity {
  NativeAdIdentity({
    required this.placement,
    required this.adType,
    required this.generation,
  });

  String placement;

  NativeAdType adType;

  int generation;

  List<Object?> _toList() {
    return <Object?>[
      placement,
      adType,
      generation,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAdIdentity decode(Object result) {
    result as List<Object?>;
    return NativeAdIdentity(
      placement: result[0]! as String,
      adType: result[1]! as NativeAdType,
      generation: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAdIdentity || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(placement, other.placement) && _deepEquals(adType, other.adType) && _deepEquals(generation, other.generation);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAdIdentity(placement: $placement, adType: $adType, generation: $generation)';
  }
}

class NativeDiagnostic {
  NativeDiagnostic({
    required this.normalizedCode,
    required this.message,
    this.nativeCode,
    this.nativeDomain,
    this.nativeMessage,
    required this.details,
  });

  String normalizedCode;

  String message;

  String? nativeCode;

  String? nativeDomain;

  String? nativeMessage;

  Map<String, String> details;

  List<Object?> _toList() {
    return <Object?>[
      normalizedCode,
      message,
      nativeCode,
      nativeDomain,
      nativeMessage,
      details,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeDiagnostic decode(Object result) {
    result as List<Object?>;
    return NativeDiagnostic(
      normalizedCode: result[0]! as String,
      message: result[1]! as String,
      nativeCode: result[2] as String?,
      nativeDomain: result[3] as String?,
      nativeMessage: result[4] as String?,
      details: (result[5]! as Map<Object?, Object?>).cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeDiagnostic || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(normalizedCode, other.normalizedCode) && _deepEquals(message, other.message) && _deepEquals(nativeCode, other.nativeCode) && _deepEquals(nativeDomain, other.nativeDomain) && _deepEquals(nativeMessage, other.nativeMessage) && _deepEquals(details, other.details);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeDiagnostic(normalizedCode: $normalizedCode, message: $message, nativeCode: $nativeCode, nativeDomain: $nativeDomain, nativeMessage: $nativeMessage, details: $details)';
  }
}

class NativeRewardResult {
  NativeRewardResult({
    required this.rewarded,
    required this.verified,
    this.rewardName,
    this.rewardAmount,
  });

  bool rewarded;

  bool verified;

  String? rewardName;

  int? rewardAmount;

  List<Object?> _toList() {
    return <Object?>[
      rewarded,
      verified,
      rewardName,
      rewardAmount,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeRewardResult decode(Object result) {
    result as List<Object?>;
    return NativeRewardResult(
      rewarded: result[0]! as bool,
      verified: result[1]! as bool,
      rewardName: result[2] as String?,
      rewardAmount: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeRewardResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(rewarded, other.rewarded) && _deepEquals(verified, other.verified) && _deepEquals(rewardName, other.rewardName) && _deepEquals(rewardAmount, other.rewardAmount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeRewardResult(rewarded: $rewarded, verified: $verified, rewardName: $rewardName, rewardAmount: $rewardAmount)';
  }
}

class NativeRevenue {
  NativeRevenue({
    this.networkName,
    this.networkPlacementId,
    this.rawEcpm,
    this.requestId,
  });

  String? networkName;

  String? networkPlacementId;

  String? rawEcpm;

  String? requestId;

  List<Object?> _toList() {
    return <Object?>[
      networkName,
      networkPlacementId,
      rawEcpm,
      requestId,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeRevenue decode(Object result) {
    result as List<Object?>;
    return NativeRevenue(
      networkName: result[0] as String?,
      networkPlacementId: result[1] as String?,
      rawEcpm: result[2] as String?,
      requestId: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeRevenue || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(networkName, other.networkName) && _deepEquals(networkPlacementId, other.networkPlacementId) && _deepEquals(rawEcpm, other.rawEcpm) && _deepEquals(requestId, other.requestId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeRevenue(networkName: $networkName, networkPlacementId: $networkPlacementId, rawEcpm: $rawEcpm, requestId: $requestId)';
  }
}

class NativeShowResult {
  NativeShowResult({
    this.reward,
  });

  NativeRewardResult? reward;

  List<Object?> _toList() {
    return <Object?>[
      reward,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeShowResult decode(Object result) {
    result as List<Object?>;
    return NativeShowResult(
      reward: result[0] as NativeRewardResult?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeShowResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(reward, other.reward);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeShowResult(reward: $reward)';
  }
}

class NativeAdEvent {
  NativeAdEvent({
    required this.kind,
    required this.placement,
    required this.adType,
    required this.generation,
    this.error,
    this.reward,
    this.revenue,
  });

  NativeEventKind kind;

  String placement;

  NativeAdType adType;

  int generation;

  NativeDiagnostic? error;

  NativeRewardResult? reward;

  NativeRevenue? revenue;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      placement,
      adType,
      generation,
      error,
      reward,
      revenue,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAdEvent decode(Object result) {
    result as List<Object?>;
    return NativeAdEvent(
      kind: result[0]! as NativeEventKind,
      placement: result[1]! as String,
      adType: result[2]! as NativeAdType,
      generation: result[3]! as int,
      error: result[4] as NativeDiagnostic?,
      reward: result[5] as NativeRewardResult?,
      revenue: result[6] as NativeRevenue?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAdEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(placement, other.placement) && _deepEquals(adType, other.adType) && _deepEquals(generation, other.generation) && _deepEquals(error, other.error) && _deepEquals(reward, other.reward) && _deepEquals(revenue, other.revenue);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAdEvent(kind: $kind, placement: $placement, adType: $adType, generation: $generation, error: $error, reward: $reward, revenue: $revenue)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeAdType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is NativeEventKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is NativeConsent) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is NativeAccess) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is NativeInitializationRequest) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is NativePrivacyUpdate) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is NativeRewardOptions) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is NativeAdRequest) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is NativeAdIdentity) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is NativeDiagnostic) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is NativeRewardResult) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is NativeRevenue) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is NativeShowResult) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is NativeAdEvent) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeAdType.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeEventKind.values[value];
      case 131:
        return NativeConsent.decode(readValue(buffer)!);
      case 132:
        return NativeAccess.decode(readValue(buffer)!);
      case 133:
        return NativeInitializationRequest.decode(readValue(buffer)!);
      case 134:
        return NativePrivacyUpdate.decode(readValue(buffer)!);
      case 135:
        return NativeRewardOptions.decode(readValue(buffer)!);
      case 136:
        return NativeAdRequest.decode(readValue(buffer)!);
      case 137:
        return NativeAdIdentity.decode(readValue(buffer)!);
      case 138:
        return NativeDiagnostic.decode(readValue(buffer)!);
      case 139:
        return NativeRewardResult.decode(readValue(buffer)!);
      case 140:
        return NativeRevenue.decode(readValue(buffer)!);
      case 141:
        return NativeShowResult.decode(readValue(buffer)!);
      case 142:
        return NativeAdEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class GroMoreHostApi {
  /// Constructor for [GroMoreHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  GroMoreHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initialize(NativeInitializationRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.initialize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> updatePrivacy(NativePrivacyUpdate request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.updatePrivacy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> loadAd(NativeAdRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.loadAd$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<bool> isReady(NativeAdIdentity identity) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.isReady$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[identity]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<NativeShowResult> showAd(NativeAdIdentity identity) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.showAd$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[identity]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeShowResult;
  }

  Future<void> dispose() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class GroMoreFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onEvent(NativeAdEvent event);

  static void setUp(GroMoreFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.owl_ads_gromore.GroMoreFlutterApi.onEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NativeAdEvent arg_event = args[0]! as NativeAdEvent;
          try {
            api.onEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
