// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum GromoreApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum NativeAdType: Int, CaseIterable {
  case reward = 0
  case insert = 1
}

enum NativeEventKind: Int, CaseIterable {
  case loaded = 0
  case shown = 1
  case clicked = 2
  case closed = 3
  case failed = 4
  case rewarded = 5
  case revenue = 6
  case unknown = 7
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeConsent: Hashable, CustomStringConvertible {
  var accepted: Bool
  var personalizedAds: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeConsent? {
    let accepted = pigeonVar_list[0] as! Bool
    let personalizedAds = pigeonVar_list[1] as! Bool

    return NativeConsent(
      accepted: accepted,
      personalizedAds: personalizedAds
    )
  }
  func toList() -> [Any?] {
    return [
      accepted,
      personalizedAds,
    ]
  }
  static func == (lhs: NativeConsent, rhs: NativeConsent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return GromoreApiPigeonInternal.deepEquals(lhs.accepted, rhs.accepted) && GromoreApiPigeonInternal.deepEquals(lhs.personalizedAds, rhs.personalizedAds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeConsent")
    GromoreApiPigeonInternal.deepHash(value: accepted, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: personalizedAds, hasher: &hasher)
  }

  public var description: String {
    return "NativeConsent(accepted: \(String(describing: accepted)), personalizedAds: \(String(describing: personalizedAds)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAccess: Hashable, CustomStringConvertible {
  var canUseLocation: Bool
  var canUsePhoneState: Bool
  var canUseWifiState: Bool
  var canUseWriteExternalStorage: Bool
  var canUseOaid: Bool
  var canUseAndroidId: Bool
  var canUseInstalledApps: Bool
  var canUseRecordAudio: Bool
  var canUseIdfa: Bool
  var canUploadDeviceInfo: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAccess? {
    let canUseLocation = pigeonVar_list[0] as! Bool
    let canUsePhoneState = pigeonVar_list[1] as! Bool
    let canUseWifiState = pigeonVar_list[2] as! Bool
    let canUseWriteExternalStorage = pigeonVar_list[3] as! Bool
    let canUseOaid = pigeonVar_list[4] as! Bool
    let canUseAndroidId = pigeonVar_list[5] as! Bool
    let canUseInstalledApps = pigeonVar_list[6] as! Bool
    let canUseRecordAudio = pigeonVar_list[7] as! Bool
    let canUseIdfa = pigeonVar_list[8] as! Bool
    let canUploadDeviceInfo = pigeonVar_list[9] as! Bool

    return NativeAccess(
      canUseLocation: canUseLocation,
      canUsePhoneState: canUsePhoneState,
      canUseWifiState: canUseWifiState,
      canUseWriteExternalStorage: canUseWriteExternalStorage,
      canUseOaid: canUseOaid,
      canUseAndroidId: canUseAndroidId,
      canUseInstalledApps: canUseInstalledApps,
      canUseRecordAudio: canUseRecordAudio,
      canUseIdfa: canUseIdfa,
      canUploadDeviceInfo: canUploadDeviceInfo
    )
  }
  func toList() -> [Any?] {
    return [
      canUseLocation,
      canUsePhoneState,
      canUseWifiState,
      canUseWriteExternalStorage,
      canUseOaid,
      canUseAndroidId,
      canUseInstalledApps,
      canUseRecordAudio,
      canUseIdfa,
      canUploadDeviceInfo,
    ]
  }
  static func == (lhs: NativeAccess, rhs: NativeAccess) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return GromoreApiPigeonInternal.deepEquals(lhs.canUseLocation, rhs.canUseLocation) && GromoreApiPigeonInternal.deepEquals(lhs.canUsePhoneState, rhs.canUsePhoneState) && GromoreApiPigeonInternal.deepEquals(lhs.canUseWifiState, rhs.canUseWifiState) && GromoreApiPigeonInternal.deepEquals(lhs.canUseWriteExternalStorage, rhs.canUseWriteExternalStorage) && GromoreApiPigeonInternal.deepEquals(lhs.canUseOaid, rhs.canUseOaid) && GromoreApiPigeonInternal.deepEquals(lhs.canUseAndroidId, rhs.canUseAndroidId) && GromoreApiPigeonInternal.deepEquals(lhs.canUseInstalledApps, rhs.canUseInstalledApps) && GromoreApiPigeonInternal.deepEquals(lhs.canUseRecordAudio, rhs.canUseRecordAudio) && GromoreApiPigeonInternal.deepEquals(lhs.canUseIdfa, rhs.canUseIdfa) && GromoreApiPigeonInternal.deepEquals(lhs.canUploadDeviceInfo, rhs.canUploadDeviceInfo)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAccess")
    GromoreApiPigeonInternal.deepHash(value: canUseLocation, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: canUsePhoneState, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: canUseWifiState, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: canUseWriteExternalStorage, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: canUseOaid, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: canUseAndroidId, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: canUseInstalledApps, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: canUseRecordAudio, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: canUseIdfa, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: canUploadDeviceInfo, hasher: &hasher)
  }

  public var description: String {
    return "NativeAccess(canUseLocation: \(String(describing: canUseLocation)), canUsePhoneState: \(String(describing: canUsePhoneState)), canUseWifiState: \(String(describing: canUseWifiState)), canUseWriteExternalStorage: \(String(describing: canUseWriteExternalStorage)), canUseOaid: \(String(describing: canUseOaid)), canUseAndroidId: \(String(describing: canUseAndroidId)), canUseInstalledApps: \(String(describing: canUseInstalledApps)), canUseRecordAudio: \(String(describing: canUseRecordAudio)), canUseIdfa: \(String(describing: canUseIdfa)), canUploadDeviceInfo: \(String(describing: canUploadDeviceInfo)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeInitializationRequest: Hashable, CustomStringConvertible {
  var appId: String
  var consent: NativeConsent
  var access: NativeAccess
  var debugLogging: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeInitializationRequest? {
    let appId = pigeonVar_list[0] as! String
    let consent = pigeonVar_list[1] as! NativeConsent
    let access = pigeonVar_list[2] as! NativeAccess
    let debugLogging = pigeonVar_list[3] as! Bool

    return NativeInitializationRequest(
      appId: appId,
      consent: consent,
      access: access,
      debugLogging: debugLogging
    )
  }
  func toList() -> [Any?] {
    return [
      appId,
      consent,
      access,
      debugLogging,
    ]
  }
  static func == (lhs: NativeInitializationRequest, rhs: NativeInitializationRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return GromoreApiPigeonInternal.deepEquals(lhs.appId, rhs.appId) && GromoreApiPigeonInternal.deepEquals(lhs.consent, rhs.consent) && GromoreApiPigeonInternal.deepEquals(lhs.access, rhs.access) && GromoreApiPigeonInternal.deepEquals(lhs.debugLogging, rhs.debugLogging)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeInitializationRequest")
    GromoreApiPigeonInternal.deepHash(value: appId, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: consent, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: access, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: debugLogging, hasher: &hasher)
  }

  public var description: String {
    return "NativeInitializationRequest(appId: \(String(describing: appId)), consent: \(String(describing: consent)), access: \(String(describing: access)), debugLogging: \(String(describing: debugLogging)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativePrivacyUpdate: Hashable, CustomStringConvertible {
  var consent: NativeConsent
  var access: NativeAccess


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePrivacyUpdate? {
    let consent = pigeonVar_list[0] as! NativeConsent
    let access = pigeonVar_list[1] as! NativeAccess

    return NativePrivacyUpdate(
      consent: consent,
      access: access
    )
  }
  func toList() -> [Any?] {
    return [
      consent,
      access,
    ]
  }
  static func == (lhs: NativePrivacyUpdate, rhs: NativePrivacyUpdate) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return GromoreApiPigeonInternal.deepEquals(lhs.consent, rhs.consent) && GromoreApiPigeonInternal.deepEquals(lhs.access, rhs.access)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativePrivacyUpdate")
    GromoreApiPigeonInternal.deepHash(value: consent, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: access, hasher: &hasher)
  }

  public var description: String {
    return "NativePrivacyUpdate(consent: \(String(describing: consent)), access: \(String(describing: access)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeRewardOptions: Hashable, CustomStringConvertible {
  var userId: String? = nil
  var rewardName: String? = nil
  var rewardAmount: Int64? = nil
  var customData: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeRewardOptions? {
    let userId: String? = nilOrValue(pigeonVar_list[0])
    let rewardName: String? = nilOrValue(pigeonVar_list[1])
    let rewardAmount: Int64? = nilOrValue(pigeonVar_list[2])
    let customData: String? = nilOrValue(pigeonVar_list[3])

    return NativeRewardOptions(
      userId: userId,
      rewardName: rewardName,
      rewardAmount: rewardAmount,
      customData: customData
    )
  }
  func toList() -> [Any?] {
    return [
      userId,
      rewardName,
      rewardAmount,
      customData,
    ]
  }
  static func == (lhs: NativeRewardOptions, rhs: NativeRewardOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return GromoreApiPigeonInternal.deepEquals(lhs.userId, rhs.userId) && GromoreApiPigeonInternal.deepEquals(lhs.rewardName, rhs.rewardName) && GromoreApiPigeonInternal.deepEquals(lhs.rewardAmount, rhs.rewardAmount) && GromoreApiPigeonInternal.deepEquals(lhs.customData, rhs.customData)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeRewardOptions")
    GromoreApiPigeonInternal.deepHash(value: userId, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: rewardName, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: rewardAmount, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: customData, hasher: &hasher)
  }

  public var description: String {
    return "NativeRewardOptions(userId: \(String(describing: userId)), rewardName: \(String(describing: rewardName)), rewardAmount: \(String(describing: rewardAmount)), customData: \(String(describing: customData)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAdRequest: Hashable, CustomStringConvertible {
  var placement: String
  var adType: NativeAdType
  var codeId: String
  var generation: Int64
  var rewardOptions: NativeRewardOptions? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAdRequest? {
    let placement = pigeonVar_list[0] as! String
    let adType = pigeonVar_list[1] as! NativeAdType
    let codeId = pigeonVar_list[2] as! String
    let generation = pigeonVar_list[3] as! Int64
    let rewardOptions: NativeRewardOptions? = nilOrValue(pigeonVar_list[4])

    return NativeAdRequest(
      placement: placement,
      adType: adType,
      codeId: codeId,
      generation: generation,
      rewardOptions: rewardOptions
    )
  }
  func toList() -> [Any?] {
    return [
      placement,
      adType,
      codeId,
      generation,
      rewardOptions,
    ]
  }
  static func == (lhs: NativeAdRequest, rhs: NativeAdRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return GromoreApiPigeonInternal.deepEquals(lhs.placement, rhs.placement) && GromoreApiPigeonInternal.deepEquals(lhs.adType, rhs.adType) && GromoreApiPigeonInternal.deepEquals(lhs.codeId, rhs.codeId) && GromoreApiPigeonInternal.deepEquals(lhs.generation, rhs.generation) && GromoreApiPigeonInternal.deepEquals(lhs.rewardOptions, rhs.rewardOptions)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAdRequest")
    GromoreApiPigeonInternal.deepHash(value: placement, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: adType, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: codeId, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: generation, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: rewardOptions, hasher: &hasher)
  }

  public var description: String {
    return "NativeAdRequest(placement: \(String(describing: placement)), adType: \(String(describing: adType)), codeId: \(String(describing: codeId)), generation: \(String(describing: generation)), rewardOptions: \(String(describing: rewardOptions)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAdIdentity: Hashable, CustomStringConvertible {
  var placement: String
  var adType: NativeAdType
  var generation: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAdIdentity? {
    let placement = pigeonVar_list[0] as! String
    let adType = pigeonVar_list[1] as! NativeAdType
    let generation = pigeonVar_list[2] as! Int64

    return NativeAdIdentity(
      placement: placement,
      adType: adType,
      generation: generation
    )
  }
  func toList() -> [Any?] {
    return [
      placement,
      adType,
      generation,
    ]
  }
  static func == (lhs: NativeAdIdentity, rhs: NativeAdIdentity) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return GromoreApiPigeonInternal.deepEquals(lhs.placement, rhs.placement) && GromoreApiPigeonInternal.deepEquals(lhs.adType, rhs.adType) && GromoreApiPigeonInternal.deepEquals(lhs.generation, rhs.generation)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAdIdentity")
    GromoreApiPigeonInternal.deepHash(value: placement, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: adType, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: generation, hasher: &hasher)
  }

  public var description: String {
    return "NativeAdIdentity(placement: \(String(describing: placement)), adType: \(String(describing: adType)), generation: \(String(describing: generation)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeDiagnostic: Hashable, CustomStringConvertible {
  var normalizedCode: String
  var message: String
  var nativeCode: String? = nil
  var nativeDomain: String? = nil
  var nativeMessage: String? = nil
  var details: [String: String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeDiagnostic? {
    let normalizedCode = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String
    let nativeCode: String? = nilOrValue(pigeonVar_list[2])
    let nativeDomain: String? = nilOrValue(pigeonVar_list[3])
    let nativeMessage: String? = nilOrValue(pigeonVar_list[4])
    let details = pigeonVar_list[5] as! [String: String]

    return NativeDiagnostic(
      normalizedCode: normalizedCode,
      message: message,
      nativeCode: nativeCode,
      nativeDomain: nativeDomain,
      nativeMessage: nativeMessage,
      details: details
    )
  }
  func toList() -> [Any?] {
    return [
      normalizedCode,
      message,
      nativeCode,
      nativeDomain,
      nativeMessage,
      details,
    ]
  }
  static func == (lhs: NativeDiagnostic, rhs: NativeDiagnostic) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return GromoreApiPigeonInternal.deepEquals(lhs.normalizedCode, rhs.normalizedCode) && GromoreApiPigeonInternal.deepEquals(lhs.message, rhs.message) && GromoreApiPigeonInternal.deepEquals(lhs.nativeCode, rhs.nativeCode) && GromoreApiPigeonInternal.deepEquals(lhs.nativeDomain, rhs.nativeDomain) && GromoreApiPigeonInternal.deepEquals(lhs.nativeMessage, rhs.nativeMessage) && GromoreApiPigeonInternal.deepEquals(lhs.details, rhs.details)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeDiagnostic")
    GromoreApiPigeonInternal.deepHash(value: normalizedCode, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: message, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: nativeCode, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: nativeDomain, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: nativeMessage, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: details, hasher: &hasher)
  }

  public var description: String {
    return "NativeDiagnostic(normalizedCode: \(String(describing: normalizedCode)), message: \(String(describing: message)), nativeCode: \(String(describing: nativeCode)), nativeDomain: \(String(describing: nativeDomain)), nativeMessage: \(String(describing: nativeMessage)), details: \(String(describing: details)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeRewardResult: Hashable, CustomStringConvertible {
  var rewarded: Bool
  var verified: Bool
  var rewardName: String? = nil
  var rewardAmount: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeRewardResult? {
    let rewarded = pigeonVar_list[0] as! Bool
    let verified = pigeonVar_list[1] as! Bool
    let rewardName: String? = nilOrValue(pigeonVar_list[2])
    let rewardAmount: Int64? = nilOrValue(pigeonVar_list[3])

    return NativeRewardResult(
      rewarded: rewarded,
      verified: verified,
      rewardName: rewardName,
      rewardAmount: rewardAmount
    )
  }
  func toList() -> [Any?] {
    return [
      rewarded,
      verified,
      rewardName,
      rewardAmount,
    ]
  }
  static func == (lhs: NativeRewardResult, rhs: NativeRewardResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return GromoreApiPigeonInternal.deepEquals(lhs.rewarded, rhs.rewarded) && GromoreApiPigeonInternal.deepEquals(lhs.verified, rhs.verified) && GromoreApiPigeonInternal.deepEquals(lhs.rewardName, rhs.rewardName) && GromoreApiPigeonInternal.deepEquals(lhs.rewardAmount, rhs.rewardAmount)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeRewardResult")
    GromoreApiPigeonInternal.deepHash(value: rewarded, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: verified, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: rewardName, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: rewardAmount, hasher: &hasher)
  }

  public var description: String {
    return "NativeRewardResult(rewarded: \(String(describing: rewarded)), verified: \(String(describing: verified)), rewardName: \(String(describing: rewardName)), rewardAmount: \(String(describing: rewardAmount)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeRevenue: Hashable, CustomStringConvertible {
  var networkName: String? = nil
  var networkPlacementId: String? = nil
  var rawEcpm: String? = nil
  var requestId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeRevenue? {
    let networkName: String? = nilOrValue(pigeonVar_list[0])
    let networkPlacementId: String? = nilOrValue(pigeonVar_list[1])
    let rawEcpm: String? = nilOrValue(pigeonVar_list[2])
    let requestId: String? = nilOrValue(pigeonVar_list[3])

    return NativeRevenue(
      networkName: networkName,
      networkPlacementId: networkPlacementId,
      rawEcpm: rawEcpm,
      requestId: requestId
    )
  }
  func toList() -> [Any?] {
    return [
      networkName,
      networkPlacementId,
      rawEcpm,
      requestId,
    ]
  }
  static func == (lhs: NativeRevenue, rhs: NativeRevenue) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return GromoreApiPigeonInternal.deepEquals(lhs.networkName, rhs.networkName) && GromoreApiPigeonInternal.deepEquals(lhs.networkPlacementId, rhs.networkPlacementId) && GromoreApiPigeonInternal.deepEquals(lhs.rawEcpm, rhs.rawEcpm) && GromoreApiPigeonInternal.deepEquals(lhs.requestId, rhs.requestId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeRevenue")
    GromoreApiPigeonInternal.deepHash(value: networkName, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: networkPlacementId, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: rawEcpm, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: requestId, hasher: &hasher)
  }

  public var description: String {
    return "NativeRevenue(networkName: \(String(describing: networkName)), networkPlacementId: \(String(describing: networkPlacementId)), rawEcpm: \(String(describing: rawEcpm)), requestId: \(String(describing: requestId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeShowResult: Hashable, CustomStringConvertible {
  var reward: NativeRewardResult? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeShowResult? {
    let reward: NativeRewardResult? = nilOrValue(pigeonVar_list[0])

    return NativeShowResult(
      reward: reward
    )
  }
  func toList() -> [Any?] {
    return [
      reward
    ]
  }
  static func == (lhs: NativeShowResult, rhs: NativeShowResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return GromoreApiPigeonInternal.deepEquals(lhs.reward, rhs.reward)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeShowResult")
    GromoreApiPigeonInternal.deepHash(value: reward, hasher: &hasher)
  }

  public var description: String {
    return "NativeShowResult(reward: \(String(describing: reward)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeAdEvent: Hashable, CustomStringConvertible {
  var kind: NativeEventKind
  var placement: String
  var adType: NativeAdType
  var generation: Int64
  var error: NativeDiagnostic? = nil
  var reward: NativeRewardResult? = nil
  var revenue: NativeRevenue? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeAdEvent? {
    let kind = pigeonVar_list[0] as! NativeEventKind
    let placement = pigeonVar_list[1] as! String
    let adType = pigeonVar_list[2] as! NativeAdType
    let generation = pigeonVar_list[3] as! Int64
    let error: NativeDiagnostic? = nilOrValue(pigeonVar_list[4])
    let reward: NativeRewardResult? = nilOrValue(pigeonVar_list[5])
    let revenue: NativeRevenue? = nilOrValue(pigeonVar_list[6])

    return NativeAdEvent(
      kind: kind,
      placement: placement,
      adType: adType,
      generation: generation,
      error: error,
      reward: reward,
      revenue: revenue
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      placement,
      adType,
      generation,
      error,
      reward,
      revenue,
    ]
  }
  static func == (lhs: NativeAdEvent, rhs: NativeAdEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return GromoreApiPigeonInternal.deepEquals(lhs.kind, rhs.kind) && GromoreApiPigeonInternal.deepEquals(lhs.placement, rhs.placement) && GromoreApiPigeonInternal.deepEquals(lhs.adType, rhs.adType) && GromoreApiPigeonInternal.deepEquals(lhs.generation, rhs.generation) && GromoreApiPigeonInternal.deepEquals(lhs.error, rhs.error) && GromoreApiPigeonInternal.deepEquals(lhs.reward, rhs.reward) && GromoreApiPigeonInternal.deepEquals(lhs.revenue, rhs.revenue)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeAdEvent")
    GromoreApiPigeonInternal.deepHash(value: kind, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: placement, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: adType, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: generation, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: error, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: reward, hasher: &hasher)
    GromoreApiPigeonInternal.deepHash(value: revenue, hasher: &hasher)
  }

  public var description: String {
    return "NativeAdEvent(kind: \(String(describing: kind)), placement: \(String(describing: placement)), adType: \(String(describing: adType)), generation: \(String(describing: generation)), error: \(String(describing: error)), reward: \(String(describing: reward)), revenue: \(String(describing: revenue)))"
  }
}

private class GromoreApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeAdType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NativeEventKind(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return NativeConsent.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeAccess.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeInitializationRequest.fromList(self.readValue() as! [Any?])
    case 134:
      return NativePrivacyUpdate.fromList(self.readValue() as! [Any?])
    case 135:
      return NativeRewardOptions.fromList(self.readValue() as! [Any?])
    case 136:
      return NativeAdRequest.fromList(self.readValue() as! [Any?])
    case 137:
      return NativeAdIdentity.fromList(self.readValue() as! [Any?])
    case 138:
      return NativeDiagnostic.fromList(self.readValue() as! [Any?])
    case 139:
      return NativeRewardResult.fromList(self.readValue() as! [Any?])
    case 140:
      return NativeRevenue.fromList(self.readValue() as! [Any?])
    case 141:
      return NativeShowResult.fromList(self.readValue() as! [Any?])
    case 142:
      return NativeAdEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class GromoreApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeAdType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeEventKind {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeConsent {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAccess {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeInitializationRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? NativePrivacyUpdate {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? NativeRewardOptions {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAdRequest {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAdIdentity {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? NativeDiagnostic {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? NativeRewardResult {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? NativeRevenue {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? NativeShowResult {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? NativeAdEvent {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class GromoreApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return GromoreApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return GromoreApiPigeonCodecWriter(data: data)
  }
}

class GromoreApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = GromoreApiPigeonCodec(readerWriter: GromoreApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol GroMoreHostApi {
  func initialize(request: NativeInitializationRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func updatePrivacy(request: NativePrivacyUpdate, completion: @escaping (Result<Void, Error>) -> Void)
  func loadAd(request: NativeAdRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func isReady(identity: NativeAdIdentity, completion: @escaping (Result<Bool, Error>) -> Void)
  func showAd(identity: NativeAdIdentity, completion: @escaping (Result<NativeShowResult, Error>) -> Void)
  func dispose(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class GroMoreHostApiSetup {
  static var codec: FlutterStandardMessageCodec { GromoreApiPigeonCodec.shared }
  /// Sets up an instance of `GroMoreHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: GroMoreHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeInitializationRequest
        api.initialize(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let updatePrivacyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.updatePrivacy\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePrivacyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativePrivacyUpdate
        api.updatePrivacy(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updatePrivacyChannel.setMessageHandler(nil)
    }
    let loadAdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.loadAd\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadAdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeAdRequest
        api.loadAd(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadAdChannel.setMessageHandler(nil)
    }
    let isReadyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.isReady\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isReadyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let identityArg = args[0] as! NativeAdIdentity
        api.isReady(identity: identityArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isReadyChannel.setMessageHandler(nil)
    }
    let showAdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.showAd\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showAdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let identityArg = args[0] as! NativeAdIdentity
        api.showAd(identity: identityArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      showAdChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        api.dispose { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol GroMoreFlutterApiProtocol {
  func onEvent(event eventArg: NativeAdEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class GroMoreFlutterApi: GroMoreFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: GromoreApiPigeonCodec {
    return GromoreApiPigeonCodec.shared
  }
  func onEvent(event eventArg: NativeAdEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.owl_ads_gromore.GroMoreFlutterApi.onEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
