// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.owlllwo.plugins.gromore

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object GromoreApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class NativeAdType(val raw: Int) {
  REWARD(0),
  INSERT(1);

  companion object {
    fun ofRaw(raw: Int): NativeAdType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NativeEventKind(val raw: Int) {
  LOADED(0),
  SHOWN(1),
  CLICKED(2),
  CLOSED(3),
  FAILED(4),
  REWARDED(5),
  REVENUE(6),
  UNKNOWN(7);

  companion object {
    fun ofRaw(raw: Int): NativeEventKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeConsent (
  val accepted: Boolean,
  val personalizedAds: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeConsent {
      val accepted = pigeonVar_list[0] as Boolean
      val personalizedAds = pigeonVar_list[1] as Boolean
      return NativeConsent(accepted, personalizedAds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accepted,
      personalizedAds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeConsent
    return GromoreApiPigeonUtils.deepEquals(this.accepted, other.accepted) && GromoreApiPigeonUtils.deepEquals(this.personalizedAds, other.personalizedAds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.accepted)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.personalizedAds)
    return result
  }
  override fun toString(): String {
    return "NativeConsent(accepted=$accepted, personalizedAds=$personalizedAds)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAccess (
  val canUseLocation: Boolean,
  val canUsePhoneState: Boolean,
  val canUseWifiState: Boolean,
  val canUseWriteExternalStorage: Boolean,
  val canUseOaid: Boolean,
  val canUseAndroidId: Boolean,
  val canUseInstalledApps: Boolean,
  val canUseRecordAudio: Boolean,
  val canUseIdfa: Boolean,
  val canUploadDeviceInfo: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAccess {
      val canUseLocation = pigeonVar_list[0] as Boolean
      val canUsePhoneState = pigeonVar_list[1] as Boolean
      val canUseWifiState = pigeonVar_list[2] as Boolean
      val canUseWriteExternalStorage = pigeonVar_list[3] as Boolean
      val canUseOaid = pigeonVar_list[4] as Boolean
      val canUseAndroidId = pigeonVar_list[5] as Boolean
      val canUseInstalledApps = pigeonVar_list[6] as Boolean
      val canUseRecordAudio = pigeonVar_list[7] as Boolean
      val canUseIdfa = pigeonVar_list[8] as Boolean
      val canUploadDeviceInfo = pigeonVar_list[9] as Boolean
      return NativeAccess(canUseLocation, canUsePhoneState, canUseWifiState, canUseWriteExternalStorage, canUseOaid, canUseAndroidId, canUseInstalledApps, canUseRecordAudio, canUseIdfa, canUploadDeviceInfo)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      canUseLocation,
      canUsePhoneState,
      canUseWifiState,
      canUseWriteExternalStorage,
      canUseOaid,
      canUseAndroidId,
      canUseInstalledApps,
      canUseRecordAudio,
      canUseIdfa,
      canUploadDeviceInfo,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAccess
    return GromoreApiPigeonUtils.deepEquals(this.canUseLocation, other.canUseLocation) && GromoreApiPigeonUtils.deepEquals(this.canUsePhoneState, other.canUsePhoneState) && GromoreApiPigeonUtils.deepEquals(this.canUseWifiState, other.canUseWifiState) && GromoreApiPigeonUtils.deepEquals(this.canUseWriteExternalStorage, other.canUseWriteExternalStorage) && GromoreApiPigeonUtils.deepEquals(this.canUseOaid, other.canUseOaid) && GromoreApiPigeonUtils.deepEquals(this.canUseAndroidId, other.canUseAndroidId) && GromoreApiPigeonUtils.deepEquals(this.canUseInstalledApps, other.canUseInstalledApps) && GromoreApiPigeonUtils.deepEquals(this.canUseRecordAudio, other.canUseRecordAudio) && GromoreApiPigeonUtils.deepEquals(this.canUseIdfa, other.canUseIdfa) && GromoreApiPigeonUtils.deepEquals(this.canUploadDeviceInfo, other.canUploadDeviceInfo)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.canUseLocation)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.canUsePhoneState)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.canUseWifiState)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.canUseWriteExternalStorage)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.canUseOaid)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.canUseAndroidId)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.canUseInstalledApps)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.canUseRecordAudio)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.canUseIdfa)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.canUploadDeviceInfo)
    return result
  }
  override fun toString(): String {
    return "NativeAccess(canUseLocation=$canUseLocation, canUsePhoneState=$canUsePhoneState, canUseWifiState=$canUseWifiState, canUseWriteExternalStorage=$canUseWriteExternalStorage, canUseOaid=$canUseOaid, canUseAndroidId=$canUseAndroidId, canUseInstalledApps=$canUseInstalledApps, canUseRecordAudio=$canUseRecordAudio, canUseIdfa=$canUseIdfa, canUploadDeviceInfo=$canUploadDeviceInfo)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeInitializationRequest (
  val appId: String,
  val consent: NativeConsent,
  val access: NativeAccess,
  val debugLogging: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeInitializationRequest {
      val appId = pigeonVar_list[0] as String
      val consent = pigeonVar_list[1] as NativeConsent
      val access = pigeonVar_list[2] as NativeAccess
      val debugLogging = pigeonVar_list[3] as Boolean
      return NativeInitializationRequest(appId, consent, access, debugLogging)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      appId,
      consent,
      access,
      debugLogging,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeInitializationRequest
    return GromoreApiPigeonUtils.deepEquals(this.appId, other.appId) && GromoreApiPigeonUtils.deepEquals(this.consent, other.consent) && GromoreApiPigeonUtils.deepEquals(this.access, other.access) && GromoreApiPigeonUtils.deepEquals(this.debugLogging, other.debugLogging)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.appId)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.consent)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.access)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.debugLogging)
    return result
  }
  override fun toString(): String {
    return "NativeInitializationRequest(appId=$appId, consent=$consent, access=$access, debugLogging=$debugLogging)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativePrivacyUpdate (
  val consent: NativeConsent,
  val access: NativeAccess
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativePrivacyUpdate {
      val consent = pigeonVar_list[0] as NativeConsent
      val access = pigeonVar_list[1] as NativeAccess
      return NativePrivacyUpdate(consent, access)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      consent,
      access,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativePrivacyUpdate
    return GromoreApiPigeonUtils.deepEquals(this.consent, other.consent) && GromoreApiPigeonUtils.deepEquals(this.access, other.access)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.consent)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.access)
    return result
  }
  override fun toString(): String {
    return "NativePrivacyUpdate(consent=$consent, access=$access)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeRewardOptions (
  val userId: String? = null,
  val rewardName: String? = null,
  val rewardAmount: Long? = null,
  val customData: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeRewardOptions {
      val userId = pigeonVar_list[0] as String?
      val rewardName = pigeonVar_list[1] as String?
      val rewardAmount = pigeonVar_list[2] as Long?
      val customData = pigeonVar_list[3] as String?
      return NativeRewardOptions(userId, rewardName, rewardAmount, customData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      userId,
      rewardName,
      rewardAmount,
      customData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeRewardOptions
    return GromoreApiPigeonUtils.deepEquals(this.userId, other.userId) && GromoreApiPigeonUtils.deepEquals(this.rewardName, other.rewardName) && GromoreApiPigeonUtils.deepEquals(this.rewardAmount, other.rewardAmount) && GromoreApiPigeonUtils.deepEquals(this.customData, other.customData)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.userId)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.rewardName)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.rewardAmount)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.customData)
    return result
  }
  override fun toString(): String {
    return "NativeRewardOptions(userId=$userId, rewardName=$rewardName, rewardAmount=$rewardAmount, customData=$customData)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAdRequest (
  val placement: String,
  val adType: NativeAdType,
  val codeId: String,
  val generation: Long,
  val rewardOptions: NativeRewardOptions? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAdRequest {
      val placement = pigeonVar_list[0] as String
      val adType = pigeonVar_list[1] as NativeAdType
      val codeId = pigeonVar_list[2] as String
      val generation = pigeonVar_list[3] as Long
      val rewardOptions = pigeonVar_list[4] as NativeRewardOptions?
      return NativeAdRequest(placement, adType, codeId, generation, rewardOptions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      placement,
      adType,
      codeId,
      generation,
      rewardOptions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAdRequest
    return GromoreApiPigeonUtils.deepEquals(this.placement, other.placement) && GromoreApiPigeonUtils.deepEquals(this.adType, other.adType) && GromoreApiPigeonUtils.deepEquals(this.codeId, other.codeId) && GromoreApiPigeonUtils.deepEquals(this.generation, other.generation) && GromoreApiPigeonUtils.deepEquals(this.rewardOptions, other.rewardOptions)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.placement)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.adType)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.codeId)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.generation)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.rewardOptions)
    return result
  }
  override fun toString(): String {
    return "NativeAdRequest(placement=$placement, adType=$adType, codeId=$codeId, generation=$generation, rewardOptions=$rewardOptions)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAdIdentity (
  val placement: String,
  val adType: NativeAdType,
  val generation: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAdIdentity {
      val placement = pigeonVar_list[0] as String
      val adType = pigeonVar_list[1] as NativeAdType
      val generation = pigeonVar_list[2] as Long
      return NativeAdIdentity(placement, adType, generation)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      placement,
      adType,
      generation,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAdIdentity
    return GromoreApiPigeonUtils.deepEquals(this.placement, other.placement) && GromoreApiPigeonUtils.deepEquals(this.adType, other.adType) && GromoreApiPigeonUtils.deepEquals(this.generation, other.generation)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.placement)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.adType)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.generation)
    return result
  }
  override fun toString(): String {
    return "NativeAdIdentity(placement=$placement, adType=$adType, generation=$generation)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeDiagnostic (
  val normalizedCode: String,
  val message: String,
  val nativeCode: String? = null,
  val nativeDomain: String? = null,
  val nativeMessage: String? = null,
  val details: Map<String, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeDiagnostic {
      val normalizedCode = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      val nativeCode = pigeonVar_list[2] as String?
      val nativeDomain = pigeonVar_list[3] as String?
      val nativeMessage = pigeonVar_list[4] as String?
      val details = pigeonVar_list[5] as Map<String, String>
      return NativeDiagnostic(normalizedCode, message, nativeCode, nativeDomain, nativeMessage, details)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      normalizedCode,
      message,
      nativeCode,
      nativeDomain,
      nativeMessage,
      details,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeDiagnostic
    return GromoreApiPigeonUtils.deepEquals(this.normalizedCode, other.normalizedCode) && GromoreApiPigeonUtils.deepEquals(this.message, other.message) && GromoreApiPigeonUtils.deepEquals(this.nativeCode, other.nativeCode) && GromoreApiPigeonUtils.deepEquals(this.nativeDomain, other.nativeDomain) && GromoreApiPigeonUtils.deepEquals(this.nativeMessage, other.nativeMessage) && GromoreApiPigeonUtils.deepEquals(this.details, other.details)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.normalizedCode)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.message)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.nativeCode)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.nativeDomain)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.nativeMessage)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.details)
    return result
  }
  override fun toString(): String {
    return "NativeDiagnostic(normalizedCode=$normalizedCode, message=$message, nativeCode=$nativeCode, nativeDomain=$nativeDomain, nativeMessage=$nativeMessage, details=$details)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeRewardResult (
  val rewarded: Boolean,
  val verified: Boolean,
  val rewardName: String? = null,
  val rewardAmount: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeRewardResult {
      val rewarded = pigeonVar_list[0] as Boolean
      val verified = pigeonVar_list[1] as Boolean
      val rewardName = pigeonVar_list[2] as String?
      val rewardAmount = pigeonVar_list[3] as Long?
      return NativeRewardResult(rewarded, verified, rewardName, rewardAmount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rewarded,
      verified,
      rewardName,
      rewardAmount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeRewardResult
    return GromoreApiPigeonUtils.deepEquals(this.rewarded, other.rewarded) && GromoreApiPigeonUtils.deepEquals(this.verified, other.verified) && GromoreApiPigeonUtils.deepEquals(this.rewardName, other.rewardName) && GromoreApiPigeonUtils.deepEquals(this.rewardAmount, other.rewardAmount)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.rewarded)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.verified)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.rewardName)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.rewardAmount)
    return result
  }
  override fun toString(): String {
    return "NativeRewardResult(rewarded=$rewarded, verified=$verified, rewardName=$rewardName, rewardAmount=$rewardAmount)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeRevenue (
  val networkName: String? = null,
  val networkPlacementId: String? = null,
  val rawEcpm: String? = null,
  val requestId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeRevenue {
      val networkName = pigeonVar_list[0] as String?
      val networkPlacementId = pigeonVar_list[1] as String?
      val rawEcpm = pigeonVar_list[2] as String?
      val requestId = pigeonVar_list[3] as String?
      return NativeRevenue(networkName, networkPlacementId, rawEcpm, requestId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      networkName,
      networkPlacementId,
      rawEcpm,
      requestId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeRevenue
    return GromoreApiPigeonUtils.deepEquals(this.networkName, other.networkName) && GromoreApiPigeonUtils.deepEquals(this.networkPlacementId, other.networkPlacementId) && GromoreApiPigeonUtils.deepEquals(this.rawEcpm, other.rawEcpm) && GromoreApiPigeonUtils.deepEquals(this.requestId, other.requestId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.networkName)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.networkPlacementId)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.rawEcpm)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.requestId)
    return result
  }
  override fun toString(): String {
    return "NativeRevenue(networkName=$networkName, networkPlacementId=$networkPlacementId, rawEcpm=$rawEcpm, requestId=$requestId)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeShowResult (
  val reward: NativeRewardResult? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeShowResult {
      val reward = pigeonVar_list[0] as NativeRewardResult?
      return NativeShowResult(reward)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reward,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeShowResult
    return GromoreApiPigeonUtils.deepEquals(this.reward, other.reward)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.reward)
    return result
  }
  override fun toString(): String {
    return "NativeShowResult(reward=$reward)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAdEvent (
  val kind: NativeEventKind,
  val placement: String,
  val adType: NativeAdType,
  val generation: Long,
  val error: NativeDiagnostic? = null,
  val reward: NativeRewardResult? = null,
  val revenue: NativeRevenue? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAdEvent {
      val kind = pigeonVar_list[0] as NativeEventKind
      val placement = pigeonVar_list[1] as String
      val adType = pigeonVar_list[2] as NativeAdType
      val generation = pigeonVar_list[3] as Long
      val error = pigeonVar_list[4] as NativeDiagnostic?
      val reward = pigeonVar_list[5] as NativeRewardResult?
      val revenue = pigeonVar_list[6] as NativeRevenue?
      return NativeAdEvent(kind, placement, adType, generation, error, reward, revenue)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      placement,
      adType,
      generation,
      error,
      reward,
      revenue,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAdEvent
    return GromoreApiPigeonUtils.deepEquals(this.kind, other.kind) && GromoreApiPigeonUtils.deepEquals(this.placement, other.placement) && GromoreApiPigeonUtils.deepEquals(this.adType, other.adType) && GromoreApiPigeonUtils.deepEquals(this.generation, other.generation) && GromoreApiPigeonUtils.deepEquals(this.error, other.error) && GromoreApiPigeonUtils.deepEquals(this.reward, other.reward) && GromoreApiPigeonUtils.deepEquals(this.revenue, other.revenue)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.placement)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.adType)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.generation)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.error)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.reward)
    result = 31 * result + GromoreApiPigeonUtils.deepHash(this.revenue)
    return result
  }
  override fun toString(): String {
    return "NativeAdEvent(kind=$kind, placement=$placement, adType=$adType, generation=$generation, error=$error, reward=$reward, revenue=$revenue)"
  }
}
private open class GromoreApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeAdType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NativeEventKind.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeConsent.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAccess.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeInitializationRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativePrivacyUpdate.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeRewardOptions.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAdRequest.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAdIdentity.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeDiagnostic.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeRewardResult.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeRevenue.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeShowResult.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAdEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeAdType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NativeEventKind -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is NativeConsent -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeAccess -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is NativeInitializationRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NativePrivacyUpdate -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is NativeRewardOptions -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is NativeAdRequest -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is NativeAdIdentity -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is NativeDiagnostic -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is NativeRewardResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is NativeRevenue -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is NativeShowResult -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is NativeAdEvent -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface GroMoreHostApi {
  fun initialize(request: NativeInitializationRequest, callback: (Result<Unit>) -> Unit)
  fun updatePrivacy(request: NativePrivacyUpdate, callback: (Result<Unit>) -> Unit)
  fun loadAd(request: NativeAdRequest, callback: (Result<Unit>) -> Unit)
  fun isReady(identity: NativeAdIdentity, callback: (Result<Boolean>) -> Unit)
  fun showAd(identity: NativeAdIdentity, callback: (Result<NativeShowResult>) -> Unit)
  fun dispose(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by GroMoreHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      GromoreApiPigeonCodec()
    }
    /** Sets up an instance of `GroMoreHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: GroMoreHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativeInitializationRequest
            api.initialize(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(GromoreApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(GromoreApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.updatePrivacy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativePrivacyUpdate
            api.updatePrivacy(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(GromoreApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(GromoreApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.loadAd$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativeAdRequest
            api.loadAd(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(GromoreApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(GromoreApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.isReady$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val identityArg = args[0] as NativeAdIdentity
            api.isReady(identityArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(GromoreApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(GromoreApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.showAd$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val identityArg = args[0] as NativeAdIdentity
            api.showAd(identityArg) { result: Result<NativeShowResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(GromoreApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(GromoreApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.owl_ads_gromore.GroMoreHostApi.dispose$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.dispose{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(GromoreApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(GromoreApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class GroMoreFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by GroMoreFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      GromoreApiPigeonCodec()
    }
  }
  fun onEvent(eventArg: NativeAdEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.owl_ads_gromore.GroMoreFlutterApi.onEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(GromoreApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
